version: '3.8'

services:
  app:
    build: .
    container_name: library-manager-backend
    ports:
      - "8080:8080"
    environment:
      SERVER_ADDRESS: 0.0.0.0
      SERVER_PORT: 8080
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/campo_facil
      SPRING_DATASOURCE_USERNAME: admin
      SPRING_DATASOURCE_PASSWORD: manager123
    depends_on:
      - db

  db:
    image: postgres:16
    container_name: library-manager-database
    environment:
      POSTGRES_DB: campo_facil
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: manager123
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgres/data

volumes:
  postgres-data: